changelog:
  categories:
    - title: Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - ci
        - chore
        - maintenance
  exclude:
    labels:
      - skip-changelog
